import { SvelteJSONEditor } from "./SvelteJSONEditor";
import { useState } from "react";
import "./styles.css";
import { Container, Row, Col, CardDeck, Card } from "react-bootstrap";
import "bootstrap/dist/css/bootstrap.min.css";
const json = {
  _id: {
    $oid: "624df73c3b29036234432db1"
  },
  name: "sip-ingress-xx",
  connections: ["cfgpxy-mf-xx", "sip-agt-xx"],
  AutoRestart: 2,
  CommandLine: "sip_server.exe",
  CommandLineArguments: "{{.commandLine}}",
  ComponentType: 0,
  FlexibleProperties: {
    CONN_INFO: {
      CFGSwitch: {
        "113": {}
      }
    }
  },
  IsPrimary: 2,
  IsServer: 2,
  ObjectPath:
    "\\Configuration\\Environment\\Applications\\Services\\{{.geoLocation}}\\SIP Servers\\Ingress",
  Options: {
    "agent-reservation": {
      "collect-lower-priority-requests": "true",
      "reject-subsequent-request": "true",
      "request-collection-time": "100 msec",
      "reservation-time": "10000 msec"
    },
    "backup-sync": {
      "addp-remote-timeout": "5",
      "addp-timeout": "5",
      "addp-trace": "off",
      protocol: "addp",
      "sync-reconnect-tout": "20 sec"
    },
    "call-cleanup": {
      "cleanup-idle-tout": "0",
      "notify-idle-tout": "10",
      "periodic-check-tout": "10 min"
    },
    extrouter: {
      "cast-type":
        "route route-uui reroute direct-callid direct-uui direct-network-callid direct-notoken direct-digits direct-ani dnis-pool pullback",
      "cluster-role": "off",
      "cof-ci-defer-create": "0",
      "cof-ci-defer-delete": "0",
      "cof-ci-req-tout": "500 msec",
      "cof-ci-wait-all": "false",
      "cof-feature": "false",
      "cof-rci-tout": "10 sec",
      "compound-dn-representation": "true",
      "default-dn": "",
      "default-network-call-id-matching": "",
      "direct-digits-key": "CDT_Track_Num",
      "dn-for-unexpected-calls": "",
      "epp-tout": "0 sec",
      "event-propagation": "list",
      "match-call-once": "false",
      "network-request-timeout": "20 sec",
      "pct-ci-req-tout": "500 msec",
      "pct-rci-tout": "10 sec",
      "proxy-name": "",
      "reconnect-tout": "5 sec",
      "register-attempts": "5",
      "register-tout": "2 sec",
      "report-connid-changes": "true",
      "request-tout": "20 sec",
      "resource-allocation-mode": "circular",
      "resource-load-maximum": "0",
      "route-dn": "",
      "tcs-queue": "",
      "tcs-use": "never",
      timeout: "60 sec",
      "use-data-from": "current",
      "use-implicit-access-numbers": "false"
    },
    license: {
      "license-file": "",
      "num-of-licenses": "max",
      "num-sdn-licenses": "1"
    },
    "link-control": {
      "ha-sync-dly-lnk-conn": "false",
      "link-alarm-high": "0",
      "link-alarm-low": "0",
      "quiet-cleanup": "false",
      "quiet-startup": "false",
      "reg-delay": "10",
      "reg-silent": "true",
      "restart-cleanup-dly": "0",
      "restart-cleanup-limit": "0",
      "use-link-bandwidth": "auto"
    },
    Log: {
      all: "l:\\GCTILogs\\{{.appName}}\\{{.appName}}.all",
      expire: "50 file",
      "keep-startup-file": "true",
      message_format: "full",
      segment: "100 MB",
      verbose: "all"
    },
    "log-filter": {
      "default-filter-type": "copy"
    },
    "log-filter-data": {
      "<key-name>": ""
    },
    TServer: {
      "accept-dn-type":
        "+extension +position +acdqueue +routedn +trunk +routequeue",
      "acw-in-idle-force-ready": "true",
      "after-routing-timeout": "10",
      "after-routing-timeout-action": "notready",
      "agent-emu-login-on-call": "false",
      "agent-group": "",
      "agent-logout-on-unreg": "false",
      "agent-logout-reassoc": "false",
      "agent-no-answer-action": "notready",
      "agent-no-answer-overflow": "",
      "agent-no-answer-timeout": "15",
      "agent-only-private-calls": "false",
      "agent-strict-id": "false",
      "am-detected": "drop",
      "ani-distribution": "inbound-calls-only",
      "audio-codecs": "telephone-event,PCMA",
      "authenticate-requests": "",
      "auto-logout-ready": "false",
      "auto-logout-timeout": "0",
      "background-processing": "true",
      "background-timeout": "60 msec",
      "backup-mode": "none",
      "backwds-compat-acw-behavior": "false",
      "blind-transfer-enabled": "false",
      "bsns-call-dev-types": "+acdq +rp +rpq +xrp",
      "busy-tone": "music/busy_5sec",
      "busy-tone-duration": "5",
      "call-monitor-acw": "false",
      "call-observer-with-hold": "false",
      "call-rq-gap": "0",
      "cancel-monitor-on-disconnect": "true",
      "cancel-monitor-on-unpark": "true",
      "check-tenant-profile": "false",
      "clid-withheld-name": "PRIVATE",
      "collect-tone": "music/collect",
      "consult-user-data": "separate",
      "control-remote-vip-scripts": "true",
      "control-vip-scripts": "true",
      "convert-otherdn": "+agentid +reserveddn +fwd",
      "correct-rqid": "false",
      cos: "",
      "cpd-info-timeout": "3",
      "customer-id": "",
      "default-dn": "",
      "default-dn-type": "none",
      "default-monitor-mode": "mute",
      "default-monitor-scope": "call",
      "default-music": "{{.defaultMusic}}",
      "default-route-point": "",
      "default-video-file": "",
      "device-rq-gap": "0",
      "dial-plan": "",
      "divert-on-ringing": "false",
      "dn-del-mode": "never",
      "dn-scope": "undefined",
      "dr-forward": "off",
      "drop-nailedup-on-logout": "false",
      "dr-peer-location": "",
      "dr-peer-trunk": "",
      "dtmf-payload": "101",
      "emergency-recording-cleanup-enabled": "false",
      "emergency-recording-filename": "",
      "emulated-login-state": "ready",
      "emulate-login": "on-RP",
      "enable-busy-on-routed-calls": "true",
      "enable-ims": "false",
      "enable-unknown-gateway": "false",
      encoding: "",
      "enforce-external-domains": "{{.externalDomains}}",
      "enforce-trusted": "true",
      "event-ringing-on-100trying": "false",
      "external-registrar": "",
      "extn-no-answer-overflow": "",
      "extn-no-answer-timeout": "13",
      "fast-busy-tone": "music/atb_5sec",
      "fax-detected": "drop",
      "feature-code-park": "10",
      "feature-code-pickup": "12",
      "feature-code-retrieve": "11",
      "find-trunk-by-location": "false",
      "forced-notready": "true",
      "geo-location": "{{.geoLocation}}",
      "greeting-after-merge": "false",
      "greeting-call-type-filter": "-internal -consult",
      "greeting-delay-events": "none",
      "greeting-notification": "-started -complete",
      "greeting-repeat-once-party": "agent",
      "ims-3pcc-prefix": "",
      "ims-default-icid-prefix": "",
      "ims-default-icid-suffix": "",
      "ims-default-orig-ioi": "",
      "ims-propagate-pcvector": "false",
      "ims-puid-domain": "",
      "ims-route": "",
      "ims-sip-domain": "",
      "ims-sip-params": "",
      "ims-skip-ifc": "",
      "inbound-bsns-calls": "false",
      "info-pass-through": "",
      "inherit-bsns-type": "false",
      "init-dnis-by-ruri": "false",
      "internal-bsns-calls": "false",
      "internal-registrar-domains": "",
      "internal-registrar-enabled": "true",
      "internal-registrar-persistent": "false",
      "intrusion-enabled": "true",
      "keep-mute-after-conference": "false",
      "kpl-interval": "10",
      "kpl-loss-rate": "10,100",
      "kpl-tolerance": "3",
      "legal-guard-time": "0",
      "logout-on-disconnect": "true",
      "logout-on-out-of-service": "false",
      "log-trace-flags":
        "+iscc +cfg$dn -cfgserv +passwd +udata -devlink -sw -req -callops -conn -client",
      "make-call-alert-info": "",
      "management-port": "{{.mgmtPort}}",
      "map-sip-errors": "true",
      "max-legs-per-sm": "0",
      "max-parking-time": "0",
      "max-pred-req-delay": "3",
      "merged-user-data": "main-only",
      "monitor-consult-calls": "false",
      "monitor-internal-calls": "true",
      "msml-record-support": "false",
      "msml-support": "true",
      "music-in-conference-file": "",
      "music-in-queue-file": "",
      "music-on-pbxpark": "music/on_hold",
      "mwi-agent-enable": "false",
      "mwi-domain": "",
      "mwi-extension-enable": "false",
      "mwi-group-enable": "false",
      "mwi-host": "",
      "mwi-implicit-notify": "",
      "mwi-mode": "SUBSCRIBE",
      "mwi-notify-unregistered-dn": "false",
      "mwi-port": "{{.sipPort}}",
      "nas-indication": "none",
      "nas-private": "false",
      "network-monitoring-timeout": "1",
      "observing-routing-point": "",
      "operational-stat-timeout": "10",
      "outbound-bsns-calls": "false",
      "overload-ctrl-call-rate-capacity": "200",
      "overload-ctrl-call-tapplytreatment-requests-rate": "10",
      "overload-ctrl-call-trequests-rate": "10",
      "overload-ctrl-call-tupdateuserdata-requests-rate": "10",
      "overload-ctrl-dialog-rate-capacity": "400",
      "overload-ctrl-tc-dn-register-capacity": "1000",
      "overload-ctrl-tc-tclient-capacity": "15000",
      "overload-ctrl-tc-tclient-dnregister-capacity": "15000",
      "overload-ctrl-tc-trequests-rate": "1000",
      "overload-ctrl-threshold": "0",
      "overload-ctrl-trequests-rate": "5000",
      "override-switch-acw": "false",
      "override-to-on-divert": "false",
      "parking-music": "music/silence",
      "partition-id": "SipServerDefaultPartition",
      "p-asserted-identity": "",
      "posn-no-answer-overflow": "",
      "posn-no-answer-timeout": "15",
      "prd-dist-call-ans-time": "0",
      "predictive-call-router-timeout": "0",
      "preview-expired": "90",
      privacy: "",
      "propagated-call-type": "false",
      "reason-in-extension": "true",
      "recall-no-answer-timeout": "15",
      "record-after-merge": "false",
      "record-consult-calls": "false",
      "recording-failure-alarm-timeout": "900",
      "recording-filename": "",
      "refer-enabled": "true",
      "reg-interval": "60",
      "registrar-default-timeout": "0",
      "releasing-party-report": "true",
      "req-distrib-event-support": "no-check",
      "resolve-internal-rp-by-host": "true",
      "resolve-sip-address": "false",
      "resource-management-by-rm": "true",
      "restart-period": "20",
      "ringing-on-route-point": "true",
      "ring-tone": "music/ring_back",
      "route-failure-alarm-high-wm": "10",
      "route-failure-alarm-low-wm": "1",
      "route-failure-alarm-period": "0",
      "router-timeout": "10",
      "rq-conflict-check": "true",
      "send-200-on-clear-call": "true",
      "server-id": "to configure this option see tservers deployment manual",
      "server-role": "0",
      "session-refresh-interval": "1800",
      "set-notready-on-busy": "",
      "shutdown-sip-reject-code": "603",
      "silence-detected": "drop",
      "silence-tone": "music/silence",
      "sip-491-passthrough": "false",
      "sip-add-contact-early-dialog": "false",
      "sip-address": "{{.sipAddress}}",
      "sip-address-srv": "",
      "sip-alert-info": "",
      "sip-alert-info-consult": "",
      "sip-alert-info-external": "",
      "sip-answer-mode": "",
      "sip-block-headers": "",
      "sip-call-retain-timeout": "1",
      "sip-dtmf-send-rtp": "false",
      "sip-enable-100rel": "false",
      "sip-enable-100rel-predictivecall": "false",
      "sip-enable-call-info": "true",
      "sip-enable-call-info-extended": "true",
      "sip-enable-gdns": "true",
      "sip-enable-moh": "true",
      "sip-enable-rfc3263": "true",
      "sip-enable-sdp-application-filter": "false",
      "sip-enable-sdp-codec-filter": "false",
      "sip-error-conversion": "",
      "sip-fqdn-ip-version": "4",
      "sip-from-pass-through": "false",
      "sip-hold-rfc3264": "true",
      "sip-invite-timeout": "0",
      "sip-invite-treatment-timeout": "2",
      "sip-iptakeover-monitoring": "true",
      "sip-ip-tos": "256",
      "sip-legacy-invite-retr-interval": "false",
      "sip-link-type": "0",
      "sip-max-retry-listen": "15",
      "sip-max-uui-length": "256",
      "sip-nic-address": "{{sipNicAddress}}",
      "sip-nic-monitoring": "true",
      "sip-outbound-proxy": "false",
      "sip-pass-check": "false",
      "sip-pass-from-parameters": "",
      "sip-pass-refer-headers": "",
      "sip-port": "{{sipPort}}",
      "sip-port-tls": "",
      "sip-preserve-contact": "false",
      "sip-proxy-headers-enabled": "true",
      "sip-referxfer-bye-timeout": "0",
      "sip-replaces-mode": "0",
      "sip-respect-privacy": "true",
      "sip-retry-timeout": "30",
      "sip-ring-tone-mode": "0",
      "sip-server-info": "",
      "sip-timer-c-support": "false",
      "sip-tls-cert": "",
      "sip-tls-cert-key": "",
      "sip-tls-cipher-list": "",
      "sip-tls-crl": "",
      "sip-tls-mutual": "false",
      "sip-tls-target-name-check": "",
      "sip-tls-trusted-ca": "",
      "sip-treatment-dtmf-interruptable": "false",
      "sip-treatments-continuous": "true",
      "sip-user-agent": "",
      "sip-vip-script-down": "{{.sip-vip-script-down}}",
      "sip-vip-script-up": "{{.sip-vip-script-up}}",
      "stranded-call-redirection-limit": "4",
      "stranded-calls-overflow": "",
      "stranded-on-arrival-calls-overflow": "",
      "subscription-delay": "0",
      "subscription-event-allowed": "",
      "subscription-timeout": "180",
      "sync-emu-agent": "false",
      "timed-acw-in-idle": "true",
      "tlib-map-replace-dn": "false",
      "tlib-nic-monitoring": "true",
      "unknown-bsns-calls": "false",
      "unknown-xfer-merge-udata": "false",
      "untimed-wrap-up-value": "1000",
      "use-display-name": "false",
      "use-propagated-call-type": "never",
      "user-data-limit": "16000",
      "userdata-map-all-calls": "false",
      "userdata-map-trans-prefix": "",
      "vip-state-change-timeout": "25",
      "voice-quality-collector-uri": "",
      "wrap-up-threshold": "0",
      "wrap-up-time": "0"
    }
  },
  PortInfos: {
    Description: null,
    TransportParams: null,
    AppParams: null,
    Id: "default",
    "Connection Protocol": null,
    Port: "{{tlibPort}}"
  },
  RedundancyType: 3,
  Resources: [],
  ServerInfo: {
    Port: "{{.tlibPort}}",
    Attempts: 1,
    Timeout: 10,
    Host: "{{.host}}",
    BackupServer: "{{.backupHost}}"
  },
  ShutdownTimeout: 90,
  StartupTimeout: 90,
  StartupType: 1,
  State: 1,
  Type: 1,
  UserProperties: {
    sml: {
      autostart: "true"
    }
  },
  Version: "{{.version}}",
  WorkDirectory: "C:\\Program Files\\GCTI\\{{.appName}}"
};

export default function App() {
  const [content, setContent] = useState({
    json
  });

  return (
    <div className="App">
      <Container>
        <Row>
          <Col xs="12" lg="10" className="p-3">
            <Card>
              <Card.Body>
                <div className="editor">
                  <SvelteJSONEditor content={content} onChange={setContent} />
                </div>
              </Card.Body>
            </Card>
          </Col>
        </Row>
      </Container>
    </div>
  );
}
